### PR TITLE
Add newer Flex Structures

### PR DESCRIPTION
**Pull request by pvyParts**

### CODE REVIEW

**Comment by pvyParts** [comment]
php isn't a language i'm super familiar with, so might be a bit dodgy from a code standpoint. let me know.

**Comment by chrRtg** [comment]
Thanks mate!
Would you mind to provide some sample scans to let me test the new feature?

**Comment by pvyParts** [comment]
sure thing, i was thinking that it would be cool if the scan parser auto appended the destination of the jump gate as a note or in the name, but i havn't looked at where that would go yet

https://hastebin.com/buxacocuno.bash

**Comment by chrRtg** [comment]
Thanks for the pastebin, will look into soon but would like to finish some bigger feature and the ongoing refactoring (see current branch "CorpDirectorsEnhancements_190926").

To add a target system to a jump gate we should it tread similar to a WH which allows to add the target system.

**Comment by pvyParts** [comment]
too easy i will look into that!

**Comment by chrRtg** [comment]
Incorporated your changes to the newest version. Have not accepted the PR because I did heavy refactoring in the meantime, to complex to merge the PR.

**Pull request closed without merging**
